### ISSUE TITLE
IOError: File e:/data/code_inuse.csv does not exist

### ISSUE THREAD

**Issue by jianjunhu** [francinexue/xuefu#1]
When I run the data.py, a error appears:

E:\Anaconda\python.exe E:/xuefu-master/data.py
Traceback (most recent call last):
  File "E:/xuefu-master/data.py", line 223, in <module>
    bigVolume()
  File "E:/xuefu-master/data.py", line 205, in bigVolume
    inuse = pd.read_csv('e:/data/code_inuse.csv',index_col=0,parse_dates=[0],encoding='gbk')
  File "E:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 491, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "E:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 268, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "E:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 583, in __init__
    self._make_engine(self.engine)
  File "E:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 724, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "E:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 1093, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas\parser.pyx", line 350, in pandas.parser.TextReader.__cinit__ (pandas\parser.c:3229)
  File "pandas\parser.pyx", line 583, in pandas.parser.TextReader._setup_parser_source (pandas\parser.c:6042)
IOError: File e:/data/code_inuse.csv does not exist

Process finished with exit code 1

**Comment by 9590** [comment]
I run it in osx sucessfully by change the code 'd:/data' to './data'
